name: Quality Check
on: [pull_request] # Se activa en cada PR

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Para Angular/TS
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint "src/**/*.ts" --max-warnings=0 # Esto fallar√° si no hay prefijos "lst"

      # Para Java/Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Checkstyle
        run: mvn checkstyle:check # Usando el pom.xml que configuramos antes